name: 404 Pinger

on:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  ping:
    name: Ping the URL
    runs-on: ubuntu-latest

    steps:
      - name: Check the site
        id: hello
        uses: srt32/uptime@master
        with:
          url-to-hit: "https://example.com"
          expected-statuses: "200"
      - name: Fire webhook
        id: sendwebhook
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://canary.discord.com/api/webhooks/789155136831225897/kglZJ1H1Gi87F8p4JF1oaczLjwOvNIwGgK4cMs2vJ5Qm4oQdpX_rZsPfZswFbQvzp-Kb'
          method: 'POST'
          data: '{"content":"<@569602218731372710> Mediawiki 1.31.11 just released! `${{ steps.hello.outputs.status }}`"}'
